"""TA10 (2nd ed.) item rows — each item matches a line on the Fittings and Contents form."""

TA10_SECTIONS = [
    {
        "key": "basic_fittings",
        "title": "1. Basic fittings",
        "description": "Status of each fitting for the sale.",
        "items": [
            "Boiler",
            "Immersion heater",
            "Radiators",
            "Night storage heaters",
            "Gas fire",
            "Electric fire",
            "Central heating system (describe if not standard)",
            "Wall heaters",
            "Door bell",
            "Lighting",
            "Roof insulation",
            "Window fittings (e.g. curtain rails)",
            "Window shutters",
            "Window blinds",
            "Door fittings (e.g. hinges, locks)",
            "Burglar alarm",
            "Electric sockets",
        ],
    },
    {
        "key": "kitchen",
        "title": "2. Kitchen",
        "description": "Kitchen appliances and fittings.",
        "items": [
            "Hob",
            "Extractor hood",
            "Oven",
            "Grill",
            "Cooker",
            "Microwave",
            "Refrigerator",
            "Freezer",
            "Fridge / freezer",
            "Dishwasher",
            "Tumble dryer",
            "Washing machine",
        ],
    },
    {
        "key": "bathroom",
        "title": "3. Bathroom",
        "description": "Bathroom fittings.",
        "items": [
            "Bath",
            "Shower fittings",
            "Shower curtain",
            "Bathroom cabinet",
            "Taps",
            "Separate shower cubicle or enclosure",
            "Towel rail",
            "Soap or toothbrush holders",
            "Toilet roll holders",
            "Mirrors",
        ],
    },
    {
        "key": "carpets",
        "title": "4. Carpets",
        "description": "Carpets by area (state which rooms in your answer if needed).",
        "items": [
            "Hall, stairs and landing",
            "Living room",
            "Dining room",
            "Kitchen",
            "Bedroom 1",
            "Bedroom 2",
            "Bedroom 3",
            "Other rooms (specify in answer)",
        ],
    },
    {
        "key": "curtains",
        "title": "5. Curtains and curtain rails",
        "description": "Curtains and rails.",
        "items": ["Curtains", "Curtain rails"],
    },
    {
        "key": "light_fittings",
        "title": "6. Light fittings",
        "description": "Light fittings excluding standard ceiling roses and bare bulbs.",
        "items": ["Light fittings (describe which rooms or fittings)"],
    },
    {
        "key": "fitted_units",
        "title": "7. Fitted units",
        "description": "Built-in storage and units.",
        "items": [
            "Fitted wardrobes",
            "Built-in cupboards",
            "Shelving",
            "Other fitted units (describe)",
        ],
    },
    {
        "key": "outdoor",
        "title": "8. Outdoor area",
        "description": "Garden and outdoor items.",
        "items": [
            "Garden furniture",
            "Garden shed",
            "Greenhouse",
            "Outdoor heating or lighting",
            "Barbecue",
            "Outside ornaments",
            "Television aerial",
            "Satellite dish",
            "Clothes line",
            "Dustbin",
            "Plants and shrubs",
        ],
    },
    {
        "key": "television",
        "title": "9. Television and telephone",
        "description": "Telecom equipment.",
        "items": ["Television", "Telephone", "Cabling"],
    },
    {
        "key": "stock_of_fuel",
        "title": "10. Stock of fuel",
        "description": "Any fuel stock included.",
        "items": ["Oil", "Wood", "LPG or other (specify)"],
    },
    {
        "key": "other",
        "title": "11. Other items",
        "description": "Any other contents not listed above.",
        "items": ["Other items (describe each)"],
    },
]

TA10_SELECT_OPTIONS = [
    "Fitted and included in sale price",
    "Included in the sale",
    "Excluded from the sale",
    "None",
    "Not applicable",
]
