"""Raw TA6 (5th ed.) numbered rows extracted from official form text; used by build_portal_form_json."""

# (form_ref, question_key, question_text) — text trimmed; conversational UI clarifies sub-parts.
TA6_NUMERIC = [
    ("1", "q1_council_tax", "What Council Tax band is the property in?"),
    ("2", "q2_asking_price", "What is the asking price of the property you are selling?"),
    ("3.1", "q3_1", "Is your property freehold, leasehold, shared ownership or commonhold? Please tick all that apply."),
    ("3.2", "q3_2", "What share of the property do you own?"),
    ("3.3", "q3_3", "How much rent do you pay each year for the remaining share of the property?"),
    ("3.4", "q3_4", "What is the end date of your lease? (DD/MM/YYYY)"),
    ("3.5", "q3_5", "Have you applied to the landlord: (a) for an extension of the lease? (b) to buy the freehold? (c) to vary the terms of the lease? If Yes to any, give details of when you applied and whether accepted."),
    ("3.6", "q3_6", "How much ground rent is due each year?"),
    ("3.7", "q3_7", "Does your lease say that the ground rent increases? If Yes, give details of the next increase (date, frequency, amount)."),
    ("3.8", "q3_8", "Does the lease require you to pay service charges? (a) Have you paid service charges? If No to both, skip 3.9–3.16 per form routing."),
    ("3.9", "q3_9", "Please give the dates of your last annual service charge (from / to) (DD/MM/YYYY)."),
    ("3.10", "q3_10", "How much was your last annual service charge?"),
    ("3.11", "q3_11", "Is there a budget or known amount for the service charge this year? If Yes, describe and attach bill if available."),
    ("3.12", "q3_12", "How frequently are service charge payments due (monthly, six-monthly, quarterly, annually)?"),
    ("3.13", "q3_13", "Please provide a copy of the commonhold community statement (or state if to follow)."),
    ("3.14", "q3_14", "How many units are there in the commonhold?"),
    ("3.15", "q3_15", "How much does your unit pay annually under the commonhold assessment?"),
    ("3.16", "q3_16", "Does the commonhold have a reserve fund? How much does your unit pay annually into the reserve fund?"),
    ("3.17", "q3_17", "Do you have to pay any additional charges relating to the property (apart from council tax, utilities), e.g. management company? If Yes, give details."),
    ("3.18", "q3_18", "How much is due annually for these other charges?"),
    ("3.19", "q3_19", "Do you have to pay anything towards maintaining access roads or footpaths? If Yes, who are payments made to?"),
    ("3.20", "q3_20", "How much is due annually towards these access road or footpath costs?"),
    ("4.1", "q4_1", "Is the property a house, bungalow, flat or maisonette?"),
    ("4.2", "q4_2", "If a house or bungalow, is it detached, semi-detached, terraced or end of terrace?"),
    ("4.3", "q4_3", "What construction type or materials have been used in the property? If unsure, say not known."),
    ("4.4", "q4_4", "How many rooms does the property have (bedrooms, bathrooms, reception rooms, other — specify)?"),
    ("5.1", "q5_1", "Which services are connected (electricity, water, sewerage, heating, broadband, mobile signal, etc.)? Give details including private water if applicable."),
    ("5.2", "q5_2", "Which services are available at the property? Any known issues or restricted mobile coverage?"),
    ("6.1", "q6_1", "Is off-road parking available? Specify type (garage, allocated space, driveway)."),
    ("6.2", "q6_2", "Is a permit required for on-road parking?"),
    ("6.3", "q6_3", "If a permit is required, what is the current annual charge?"),
    ("6.4", "q6_4", "Does the property have an electric vehicle (EV) charging point? If Yes, specify make and location."),
    ("7.1", "q7_1", "Are you aware of any defects or hazards that might lead to fire or structural failure? If Yes, give details."),
    ("7.2", "q7_2", "If Yes to 7.1: have urgent or essential works been recommended? Any proposals or completed works? Give details."),
    ("8.1", "q8_1", "Is the property (or any part) in a conservation area? If Yes, supply or note documents to follow."),
    ("8.2", "q8_2", "Is the property (or any part) listed?"),
    ("8.3", "q8_3", "If listed, what grade? Supply or note relevant documents."),
    ("8.4", "q8_4", "Does your title contain restrictive covenants affecting use? Supply title copy or note to follow."),
    ("8.5", "q8_5", "Are any trees subject to a Tree Preservation Order? (a) Terms complied with? (b) Documents supplied or to follow?"),
    ("9.1", "q9_1", "Does the property benefit from rights or arrangements over neighbouring property (including rights of way)? Details."),
    ("9.2", "q9_2", "Does ownership carry responsibility to contribute to jointly used services (shared driveway, boundary, drain)? Details."),
    ("9.3", "q9_3", "Has anyone prevented access, complained, or demanded payment for access? Details."),
    ("9.4", "q9_4", "Rights of light; rights of support; customary rights — which apply? Yes / No / Not known for each with notes."),
    ("9.5", "q9_5", "Mines and minerals; chancel repair; rights to take things from the land — do any affect the property? Details."),
    ("9.6", "q9_6", "Any other rights or arrangements (including rights of way)? Details."),
    ("9.7", "q9_7", "Do drains, pipes or wires serving the property cross any neighbour’s land?"),
    ("9.8", "q9_8", "Do drains, pipes or wires to a neighbour’s property cross your land?"),
    ("9.9", "q9_9", "Any agreement about drains, pipes or wires? Copy or details."),
    ("10.1", "q10_1", "What is the flood risk for the area around the property (use gov.uk long-term flood risk if helpful)?"),
    ("10.2", "q10_2", "Has any part of the property ever been flooded? When, which parts, type of flooding, details."),
    ("10.3", "q10_3", "Are there flood defences installed? Details."),
    ("10.4", "q10_4", "If near the coast, any known coastal erosion risk? Details."),
    ("11.1", "q11_1", "Any breaches of planning or building regulations conditions, unfinished work, or work without consents? Details."),
    ("11.2", "q11_2", "Any planning or building control issues to resolve? Details."),
    ("12.1", "q12_1", "Any notices, correspondence, negotiations affecting the property or nearby? Details."),
    ("12.2", "q12_2", "Any plans or proposals to develop property or land nearby? Details."),
    ("12.3", "q12_3", "Any proposals to alter or change use of buildings nearby? Details."),
    ("13", "q13_accessibility", "Accessibility: (a) step-free access from street, (b) wet room / level access shower, (c) lateral living, (d) other adaptations — for each Yes, give details."),
    ("14", "q14_coalfield", "Are you aware the property is on a past or present coalfield or affected by other mining activity?"),
    ("15.1", "q15_1", "Looking from the road, who owns or accepts responsibility to maintain each boundary (left, right, rear, front)?"),
    ("15.2", "q15_2", "If boundaries are irregular, describe ownership or refer to a plan."),
    ("15.3", "q15_3", "Any boundary feature moved in the last 10 years or during your ownership? Details."),
    ("15.4", "q15_4", "During your ownership, was adjacent land purchased? Details for left, right, rear, front."),
    ("15.5", "q15_5", "Any overhang or projection under neighbour’s land or road (eaves, cellars, walkways)? Details."),
    ("15.6", "q15_6", "Any Party Wall etc. Act 1996 notice? Copy and details of works."),
    ("16.1", "q16_1", "Disputes or complaints about your property or nearby? When and who involved?"),
    ("16.2", "q16_2", "Anything that might lead to a dispute? Details."),
    ("16.3", "q16_3", "Do neighbours or the public have a right to enter your property? Details."),
    ("17.1", "q17_1", "Alterations: windows/roof lights since 1 Apr 2002; extension; conservatory; loft; garage conversion; internal wall removal; insulation; other — which apply (Yes/No each) and notes."),
    ("17.2", "q17_2", "If Yes to 17.1 items: details and dates. Was work completed? Planning, building regs, completion certificates — obtained? If not required, why?"),
    ("17.3", "q17_3", "Any part used exclusively for non-residential purposes? Details and documents."),
    ("17.4", "q17_4", "Solar panels installed? If Yes: year; ownership; roof lease; maintenance; battery; grid export; FIT/SEG; documentation; panel position; structural adequacy — answer all that apply."),
    ("18", "q18_consent", "Do you have consent for matters needing permission in your deeds? Details; check with solicitor."),
    ("19.1", "q19_1", "Guarantees/warranties: NHBC, damp, timber, windows, electrical, roofing, heating, underpinning, insulation — which apply? Copies supplied or to follow."),
    ("19.2", "q19_2", "Any claims under those guarantees? Details."),
    ("20.1", "q20_1", "Do you insure the property? If No, who insures?"),
    ("20.2", "q20_2", "Difficulty obtaining insurance? Details."),
    ("20.3", "q20_3", "Insurance subject to special conditions? Details."),
    ("20.4", "q20_4", "Any buildings insurance claims? Details."),
    ("21.1", "q21_1", "Do you live at the property?"),
    ("21.2", "q21_2", "Anyone else aged 17+ living there? Names; tenants or lodgers; assured shortholds or licences?"),
    ("21.3", "q21_3", "Sold with vacant possession? Explain meaning in your own words and answer."),
    ("21.4", "q21_4", "Have all occupiers aged 17+ agreed to sign the contract?"),
    ("21.5", "q21_5", "If not vacant possession: occupiers and tenancy agreements (details / copies)."),
    ("22.1", "q22_1", "Details for each connected service: mains electricity (provider, meter location, MPAN), gas (MPRN), oil, other — as applicable."),
    ("22.2", "q22_2", "Electrical installation tested by qualified electrician? Year and certificate copy."),
    ("22.3", "q22_3", "Rewired or electrical work since 1 Jan 2005? BS7671 certificate, Building Regulations compliance, or why exempt."),
    ("22.4", "q22_4", "How is the property heated? Tick all that apply; heat pump provider/model if relevant."),
    ("22.5", "q22_5", "Connected to mains foul drainage? Surface water drainage?"),
    ("22.6", "q22_6", "Septic tank, sewage treatment plant, or cesspool? If any, answer 22.7 onwards."),
    ("22.7", "q22_7", "When was the sewerage system installed (MM/YYYY)?"),
    ("22.8", "q22_8", "When was sewerage system last replaced or upgraded?"),
    ("22.9", "q22_9", "If cesspool, when last emptied?"),
    ("22.10", "q22_10", "If sewage treatment plant, when last serviced?"),
    ("22.11", "q22_11", "Discharge to ground or surface water?"),
    ("22.12", "q22_12", "If discharges to ground, infiltration system?"),
    ("22.13", "q22_13", "System shared with other properties? How many?"),
    ("22.14", "q22_14", "Any part of sewerage system or access outside your boundary? Plan if Yes."),
    ("23.1", "q23_1", "Supply a copy of the EPC (or state to follow)."),
    ("23.2", "q23_2", "Green Deal financed installations? Details and last electricity bill copy."),
    ("23.3", "q23_3", "Japanese knotweed on or adjacent to the property? Management plan in place?"),
    ("23.4", "q23_4", "Radon test carried out? Report copy; result below action level?"),
    ("23.5", "q23_5", "Remedial measures for Radon on construction? Details."),
    ("24.1", "q24_1", "Sale dependent on completing another purchase the same day?"),
    ("24.2", "q24_2", "Special requirements about moving date?"),
    ("24.3", "q24_3", "Will sale price repay all mortgages and charges?"),
    ("24.4", "q24_4", "Will seller ensure rubbish removed, property clean, only agreed contents/fixtures remain? Confirm each part."),
    ("25", "q25_additional", "Additional information you think the buyer should know about the property or area?"),
]

TA6_PREAMBLE = [
    (
        "seller_names_individual",
        "Full names of seller(s) if individuals (as on HM Land Registry title or deeds).",
    ),
    (
        "seller_capacity",
        "Capacity in which you provide information: Seller(s), Seller’s personal representative, Attorney(s), or Trustee(s).",
    ),
    (
        "seller_company",
        "If seller is a company: company name, number, director/authorised person, country of incorporation.",
    ),
    (
        "ownership_date",
        "When did you become owner or get authority to sell? (DD/MM/YYYY)",
    ),
    (
        "property_address",
        "Full address of the property being sold (all lines and postcode).",
    ),
    ("property_uprn", "Unique Property Reference Number (UPRN) of the property."),
    (
        "solicitor_details",
        "Seller’s solicitor: firm name, full address, contact name, email, reference.",
    ),
]
